### ISSUE TITLE
Monte Carlo example leads to value error (float but should be int)

### ISSUE THREAD

**Issue by MartinHaus1993** [tlamadon/pytwoway#51]
Hi there,

once again, thanks a lot for this great package!

I just came across some trouble when replicating the Monte Carlo notebook ( https://tlamadon.github.io/pytwoway/notebooks/monte_carlo_example.html ). When running the code, I run into 
`ValueError: m has the wrong dtype, it is currently float64 but should be one of the following: int`

This originates from 
```
  File "/usr/local/lib/python3.9/site-packages/pytwoway/montecarlo.py", line 167, in _monte_carlo_interior
    sim_data = sim_data.clean(clean_params_1).min_joint_obs_frame(is_sorted=True, copy=False).clean(clean_params_2)
  File "/usr/local/lib/python3.9/site-packages/bipartitepandas/bipartitelongbase.py", line 106, in clean
    frame._check_cols()
  File "/usr/local/lib/python3.9/site-packages/bipartitepandas/bipartitebase.py", line 1168, in _check_cols
    raise ValueError(error_msg)
```

I had a closer look at this, and the issue appears to be with line 64 of bipartitelongbase.py:
` frame.loc[:, 'm'] = ((i_col == i_prev) & (j_col != j_prev)).astype(int, copy=False) + ((i_col == i_next) & (j_col != j_next)).astype(int, copy=False)`

It seems that under some circumstances, the m column created becomes a float. Maybe this is the case if some values are missing or some dependency version issues at my end?

As a temporary fix, I added the line 
`frame["m"] = pd.to_numeric(frame["m"], downcast="integer")`
below line 64.

Things are running smoothly now. I hope this is useful for anyone else facing this error!

Best,
Martin

**Comment by adamoppenheimer** [comment]
Hi Martin,

Thanks for posting the issue.

At some point I plan to go through BipartitePandas and rewrite a decent amount of it, so when I get to that I'll make sure to fix this as well.

I'll close the issue since you have resolved it already.

Best,
Adam
