### ISSUE TITLE
Recovering worker and firm IDS with different estimators (version 0.3.21)

### ISSUE THREAD

**Issue by ludelgad** [tlamadon/pytwoway#58]
Hi Adam,

Thanks for maintaining this great resource! This is my first time using this package, so I am sorry in advance if something is unclear or wrong. I have run with both the simulated data from the pytwoway notebook examples and actual data the FEEstimator and the SorkinEstimator. My issue with both is that even if I include the track_id_changes=True when setting the BipartiteData Frame, I cannot recover the original IDs when using original_ids(). See below the error code I get when doing the SorkinEstimator:

<img width="580" alt="Screenshot 2024-11-04 at 8 11 40 PM" src="https://github.com/user-attachments/assets/d5c8d728-db5b-4833-82f7-7df88ffadf26">

It is something with resetting IDs in the clean(), as it works before that step. I have read and tried to replicate the solutions in issues #5 and #2, but it's been unsuccessful in my code. I'm unsure if it's related to version updating, as I use a server without internet access. Do you have other ways of recovering the IDs apart from original_ids()?

Thanks for your help!
Lukas

PD: Here is the general code I'm using (it is a snapshot, as it is much easier than extracting the code from the server).
<img width="610" alt="Screenshot 2024-11-04 at 8 36 57 PM" src="https://github.com/user-attachments/assets/6b54f671-ff6f-4034-84b7-e6a406e90a34">

**Comment by adamoppenheimer** [comment]
Hi Lukas,

Thank you for using PyTwoWay and for reaching out!

I just responded [here](https://github.com/tlamadon/bipartitepandas/issues/16) about another issue with BipartitePandas. Like I said there, unfortunately some updates to Pandas and NumPy seem to cause issue with BipartitePandas. I apologize but I haven't had time to work on this recently and don't believe I will have time in the near future either.

One potential fix is to directly include the original ids as their own column, i.e. instantiate the dataframe like this:
```python
bdf = bpd.BipartiteDataFrame(..., original_ids=df['lnr'])
```

This way it shouldn't try to convert the new column to a categorical variable and should keep the original values. Please let me know if this works!

Best,
Adam

**Comment by ludelgad** [comment]
Hi Adam,

Thanks for the quick reply! Unfortunately, I've been trying different versions of what you suggested, but it still gives me the same error, and if exporting instead the resulting bdf frame, the original IDs do not appear after the estimation. Here is the code for the FEEestimator. It should be easier to extract the original IDs, but it is not.
![Screenshot 2024-11-05 at 10 44 02 AM](https://github.com/user-attachments/assets/4be96e53-0e60-4d6e-b78d-a806af3785b9)

Thanks for your help!

Best,
Lukas

**Comment by adamoppenheimer** [comment]
Hi Lukas,

This would store the ids in the dataframe under the column name `'original_ids'`. You would extract them from the column rather than calling the `.original_ids()` function.

To access the original ids, you can run `bdf['original_ids']`.

Let me know if this works.

Best,
Adam

**Comment by ludelgad** [comment]
Hi Adam,

Thanks, that was what I thought initially, but then, when running clean(), those columns were eliminated from the bdf. So, I was unsure how to extract them after the estimation if there is no link with the new IDs. My experience with this is somewhat limited, but I've tried with the custom columns in the BipartiteData without much progress, so I'm trying to follow any suggestions you might have.

Best,
Lukas

**Comment by DavidMarguerit** [comment]
Hi,

Thank you very much for maintaining this amazing package!

I have exactly the same issue as Lukas. I tried your suggestion `bdf['original_ids']`, but it did not work.

Could you let me know if you have any other suggestions I could try?

Best,
David

**Comment by adamoppenheimer** [comment]
Sorry for the delayed response.

Here's some sample code I'm using.

I made sure to install an older version of NumPy (it seems that NumPy with versions >= 2 might not be compatible):
```
pip install 'numpy==1.26.0' --force-reinstall
```

Here's the code:
```python
import bipartitepandas as bpd
import pytwoway as tw

# Simulate data
a = bpd.SimBipartite().simulate()

# Store original firm and worker ids as separate columns
a['wid'] = a['i'].copy()
a['fid'] = a['j'].copy()

# Convert to BipartitePandas DataFrame
bdf = bpd.BipartiteDataFrame(a)

# Clean and collapse
clean_params = bpd.clean_params({'connectedness': 'connected'})
bdf = bdf.clean(clean_params).collapse()

# Initialize FE estimator
fe_params = tw.fe_params({'feonly': True, 'attach_fe_estimates': True})
fe_estimator = tw.FEEstimator(bdf, fe_params)

# Fit FE estimator
fe_estimator.fit()
```

After running this code, `bdf` contains the original ids as well as the fixed effect estimates. It seems that the original ids got converted to floats, so you could always convert them back to the correct datatype.

I hope this helps, and please let me know if you are still having issues or if any other questions come up!

Best,
Adam

**Comment by ludelgad** [comment]
Hi Adam,

No worries, and thanks for replying! I tried your solution by adjusting the Numpy version, but it still does not work!

My Numpy version is 1.19.2, Pandas is 1.1.3, and Pytwoway is 0.3.21. Despite that, from the clean and collapse stage, it drops the columns of original IDs and does not recover them in any future stage (see below).

Screenshot of a part of the code:
![Screenshot 2024-11-22 at 10 41 58 AM](https://github.com/user-attachments/assets/a8bcd1aa-8c81-458d-af97-beafb12b152e)

It passes from this: 
![Screenshot 2024-11-22 at 10 42 28 AM](https://github.com/user-attachments/assets/7b02763c-cd36-4160-ac90-493cd4e83323)

To this after the cleaning and collapsing stage: 
![Screenshot 2024-11-22 at 10 42 39 AM](https://github.com/user-attachments/assets/aa2ef6a4-8e6c-45c3-874a-95761c63e7d0)

It seems something trivial, but it's not working!

Thanks for your help,
Lukas

**Comment by adamoppenheimer** [comment]
I have a feeling this is from your Pandas version, is there a way you could use a more recent version? BipartitePandas is compatible with Pandas up to version 2.0.3.

Also, just for confirmation, what is the version of BipartitePandas you are using?

Best,
Adam

**Comment by ludelgad** [comment]
Hi Adam,

It finally worked when updating the Pandas version to 2.0.3. I also needed to transform the i's and j's to numeric variables before fitting the FEEstimator with attach_fe_estimates. Thanks for your help! 

The versions I'm finally using are Pandas 2.0.3, Numpy 1.24.4, Bipartitepandas 1.10.0, and Pytwoway 0.3.21.

Best,
Lukas

**Comment by adamoppenheimer** [comment]
Hi Lukas,

That's great! Sorry the package isn't in the best shape at the moment, I haven't had a chance to update it in quite some time.

Hi David,

Does the updated solution work for you as well? I will mark this issue as closed if everything is resolved.

Thank you!

Best,
Adam

**Comment by DavidMarguerit** [comment]
Hi,
Yes, it works also for me.
Thank you for the support and the package!
Best,
David
