### ISSUE TITLE
calling multi-processing twice?

### ISSUE THREAD

**Issue by tlamadon** [tlamadon/pytwoway#7]
https://github.com/tlamadon/pytwoway/blob/44cc224bbf468aee9ebe55e7f4b370444922a88d/pytwoway/attrition.py#L410

It looks like we are calling multiprocessing within multiprocessing. Let's take a closer look at this.

**Comment by adamoppenheimer** [comment]
The first multi-processing is set to `if False` so it doesn't ever run.
